### ISSUE TITLE
Two Africa zoneinfo raise exception in pendulum

### ISSUE THREAD

**Issue by HeathLee** [sdispater/pytzdata#8] opened 2019-02-20 07:58 UTC
timezone `Africa/Casablanca` and  `Africa/El_Aaiun` will raise `InvalidPosixSpec` exception
since version 2018.8

```python
import pendulum
pendulum.now('Africa/El_Aaiun')
pendulum.now('Africa/Casablanca')
```

**Comment by altendky** [comment] 2019-05-15 03:07
Reported again in sdispater/pendulum#370.  As noted there it looks to be fixed in https://github.com/sdispater/pendulum/commit/94d28b0d3cb524ae02361bd1ed7ea03e2e655e4e.

I would suggest closing this issue since the problem is in another library, it is fixed, and we can leave sdispater/pendulum#370 open with the request to release the fix.

**Closed** 2022-10-11 06:55 UTC
